// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImportanceController from "./importance_controller"
application.register("importance", ImportanceController)

import MarkSubtaskCompleteController from "./mark_subtask_complete_controller"
application.register("mark-subtask-complete", MarkSubtaskCompleteController)

import SubtaskController from "./subtask_controller"
application.register("subtask", SubtaskController)

import SubtaskDeleteController from "./subtask_delete_controller"
application.register("subtask-delete", SubtaskDeleteController)
